version: 0.2

phases:
  install: 
    on-failure: ABORT
    commands:
      - cd ./poc-delete-rds
      - pip install -r requirements.txt
  build:
    on-failure: ABORT
    commands:
      - python3 deleterds.py