version: 0.2

phases:
  install: 
    on-failure: ABORT
    commands:
      - cd ./poc-pipe-down/scripts
      - terraform init --upgrade
      - pip install -r requirements.txt
  build:
    on-failure: ABORT
    commands:
      - terraform apply --auto-approve
      - python3 delete-rds.py